//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellisenseless.PowerApps.WorkflowActions.ProxyClasses
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Activitypointer_deliveryprioritycode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_correlationmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConversationIndex = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomCorrelation = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InReplyTo = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Skipped = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SmartMatching = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TrackingToken = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		XHeader = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_notifications
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThemessagewassavedasaMicrosoftDynamics365emailrecordbutnotalltheattachmentscouldbesavedwithitAnattachmentcannotbesavedifitisblockedorifitsfiletypeisinvalid = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Truncatedbody = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_prioritycode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_reminderstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSet = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReminderExpired = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReminderInvalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReminderSet = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_remindertype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IfIdonotreceiveareplyby = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Iftheemailisnotopenedby = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Remindmeanywaysat = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Email_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PendingSend = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Received = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sending = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sent = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Processstage_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CloseOut = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Initiate = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planning = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 6,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Qooi_pricingerrorcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BaseCurrencyAttributeOverflow = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BaseCurrencyAttributeUnderflow = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DetailError = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DiscountTypeInvalidState = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InactiveDiscountType = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InactivePriceLevel = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidCurrentCost = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidDiscount = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidDiscountType = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPrice = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelAmount = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelCurrency = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelPercentage = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPricingCode = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPricingPrecision = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidProduct = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidQuantity = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingAmount = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingOption = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingPolicy = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidStandardCost = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingCurrentCost = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPrice = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevel = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevelAmount = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevelPercentage = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPricingCode = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProduct = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProductDefaultUOM = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProductUOMSchedule = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingQuantity = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingStandardCost = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingUnitPrice = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingUOM = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceAttributeOutOfRange = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceCalculationError = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductNotInPriceLevel = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transactioncurrencyisnotsetfortheproductpricelistitem = 38,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Qooi_skippricecalculation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoPriceCalcAlways = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SkipPriceCalcOnRetrieve = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Quote_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Quote_paymenttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Quote_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Quote_shipto_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum Quote_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress_1 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress_2 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lost = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Revised = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Won = 4,
	}
}
