//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellisenseless.PowerApps.WorkflowActions.ProxyClasses
{
	
	
	/// <summary>
	/// Stage associated with a process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("processstage")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public partial class ProcessStage : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ProcessStage() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "processstage";
		
		public const int EntityTypeCode = 4724;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Step metadata for process stage
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdata")]
		public string ClientData
		{
			get
			{
				return this.GetAttributeValue<string>("clientdata");
			}
		}
		
		/// <summary>
		/// Enter the user or team who is assigned to manage the record. This field is updated every time the record is assigned to a different user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference Owner
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
		}
		
		/// <summary>
		/// Select the business unit that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public System.Nullable<System.Guid> OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Primary entity associated with the stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentitytypecode")]
		public string PrimaryEntity
		{
			get
			{
				return this.GetAttributeValue<string>("primaryentitytypecode");
			}
			set
			{
				this.OnPropertyChanging("PrimaryEntity");
				this.SetAttributeValue("primaryentitytypecode", value);
				this.OnPropertyChanged("PrimaryEntity");
			}
		}
		
		/// <summary>
		/// Shows the ID of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public Microsoft.Xrm.Sdk.EntityReference Process
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("processid");
			}
			set
			{
				this.OnPropertyChanging("Process");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("Process");
			}
		}
		
		/// <summary>
		/// Shows the ID of the process stage record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processstageid")]
		public System.Nullable<System.Guid> ProcessStageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processstageid");
			}
			set
			{
				this.OnPropertyChanging("ProcessStageId");
				this.SetAttributeValue("processstageid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ProcessStageId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processstageid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ProcessStageId = value;
			}
		}
		
		/// <summary>
		/// Select the category of the sales process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stagecategory")]
		public Microsoft.Xrm.Sdk.OptionSetValue StageCategory
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("stagecategory");
			}
			set
			{
				this.OnPropertyChanging("StageCategory");
				this.SetAttributeValue("stagecategory", value);
				this.OnPropertyChanged("StageCategory");
			}
		}
		
		/// <summary>
		/// Type a name for the process stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stagename")]
		public string ProcessStageName
		{
			get
			{
				return this.GetAttributeValue<string>("stagename");
			}
			set
			{
				this.OnPropertyChanging("ProcessStageName");
				this.SetAttributeValue("stagename", value);
				this.OnPropertyChanged("ProcessStageName");
			}
		}
		
		/// <summary>
		/// Version number of the process stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N processstage_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("processstage_quotes")]
		public System.Collections.Generic.IEnumerable<Quote> processstage_quotes
		{
			get
			{
				return this.GetRelatedEntities<Quote>("processstage_quotes", null);
			}
			set
			{
				this.OnPropertyChanging("processstage_quotes");
				this.SetRelatedEntities<Quote>("processstage_quotes", null, value);
				this.OnPropertyChanged("processstage_quotes");
			}
		}
		
		/// <summary>
		/// N:1 process_processstage
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("process_processstage")]
		public Process process_processstage
		{
			get
			{
				return this.GetRelatedEntity<Process>("process_processstage", null);
			}
			set
			{
				this.OnPropertyChanging("process_processstage");
				this.SetRelatedEntity<Process>("process_processstage", null, value);
				this.OnPropertyChanged("process_processstage");
			}
		}
	}
}
