//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellisenseless.PowerApps.WorkflowActions.ProxyClasses
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum QuoteState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Won = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 3,
	}
	
	/// <summary>
	/// Formal offer for products and/or services, proposed at specific prices and related payment terms, which is sent to a prospective customer.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("quote")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public partial class Quote : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Quote() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "quote";
		
		public const int EntityTypeCode = 1084;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the account with which the quote is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
		public Microsoft.Xrm.Sdk.EntityReference Account
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_addressid")]
		public System.Nullable<System.Guid> BillToAddressID
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("billto_addressid");
			}
			set
			{
				this.OnPropertyChanging("BillToAddressID");
				this.SetAttributeValue("billto_addressid", value);
				this.OnPropertyChanged("BillToAddressID");
			}
		}
		
		/// <summary>
		/// Type the city for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_city")]
		public string BillToCity
		{
			get
			{
				return this.GetAttributeValue<string>("billto_city");
			}
			set
			{
				this.OnPropertyChanging("BillToCity");
				this.SetAttributeValue("billto_city", value);
				this.OnPropertyChanged("BillToCity");
			}
		}
		
		/// <summary>
		/// Shows the complete Bill To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_composite")]
		public string BillToAddress
		{
			get
			{
				return this.GetAttributeValue<string>("billto_composite");
			}
		}
		
		/// <summary>
		/// Type the primary contact name at the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_contactname")]
		public string BillToContactName
		{
			get
			{
				return this.GetAttributeValue<string>("billto_contactname");
			}
			set
			{
				this.OnPropertyChanging("BillToContactName");
				this.SetAttributeValue("billto_contactname", value);
				this.OnPropertyChanged("BillToContactName");
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_country")]
		public string BillToCountry_Region
		{
			get
			{
				return this.GetAttributeValue<string>("billto_country");
			}
			set
			{
				this.OnPropertyChanging("BillToCountry_Region");
				this.SetAttributeValue("billto_country", value);
				this.OnPropertyChanged("BillToCountry_Region");
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_fax")]
		public string BillToFax
		{
			get
			{
				return this.GetAttributeValue<string>("billto_fax");
			}
			set
			{
				this.OnPropertyChanging("BillToFax");
				this.SetAttributeValue("billto_fax", value);
				this.OnPropertyChanged("BillToFax");
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line1")]
		public string BillToStreet1
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line1");
			}
			set
			{
				this.OnPropertyChanging("BillToStreet1");
				this.SetAttributeValue("billto_line1", value);
				this.OnPropertyChanged("BillToStreet1");
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line2")]
		public string BillToStreet2
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line2");
			}
			set
			{
				this.OnPropertyChanging("BillToStreet2");
				this.SetAttributeValue("billto_line2", value);
				this.OnPropertyChanged("BillToStreet2");
			}
		}
		
		/// <summary>
		/// Type the third line of the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line3")]
		public string BillToStreet3
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line3");
			}
			set
			{
				this.OnPropertyChanging("BillToStreet3");
				this.SetAttributeValue("billto_line3", value);
				this.OnPropertyChanged("BillToStreet3");
			}
		}
		
		/// <summary>
		/// Type a name for the customer's billing address, such as "Headquarters" or "Field office", to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_name")]
		public string BillToName
		{
			get
			{
				return this.GetAttributeValue<string>("billto_name");
			}
			set
			{
				this.OnPropertyChanging("BillToName");
				this.SetAttributeValue("billto_name", value);
				this.OnPropertyChanged("BillToName");
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_postalcode")]
		public string BillToZIP_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("billto_postalcode");
			}
			set
			{
				this.OnPropertyChanging("BillToZIP_PostalCode");
				this.SetAttributeValue("billto_postalcode", value);
				this.OnPropertyChanged("BillToZIP_PostalCode");
			}
		}
		
		/// <summary>
		/// Type the state or province for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_stateorprovince")]
		public string BillToState_Province
		{
			get
			{
				return this.GetAttributeValue<string>("billto_stateorprovince");
			}
			set
			{
				this.OnPropertyChanging("BillToState_Province");
				this.SetAttributeValue("billto_stateorprovince", value);
				this.OnPropertyChanged("BillToState_Province");
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_telephone")]
		public string BillToPhone
		{
			get
			{
				return this.GetAttributeValue<string>("billto_telephone");
			}
			set
			{
				this.OnPropertyChanging("BillToPhone");
				this.SetAttributeValue("billto_telephone", value);
				this.OnPropertyChanged("BillToPhone");
			}
		}
		
		/// <summary>
		/// Shows the campaign that the order was created from.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignid")]
		public Microsoft.Xrm.Sdk.EntityReference SourceCampaign
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("campaignid");
			}
			set
			{
				this.OnPropertyChanging("SourceCampaign");
				this.SetAttributeValue("campaignid", value);
				this.OnPropertyChanged("SourceCampaign");
			}
		}
		
		/// <summary>
		/// Enter the date when the quote was closed to indicate the expiration, revision, or cancellation date.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("closedon")]
		public System.Nullable<System.DateTime> ClosedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("closedon");
			}
			set
			{
				this.OnPropertyChanging("ClosedOn");
				this.SetAttributeValue("closedon", value);
				this.OnPropertyChanged("ClosedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the contact associated with the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
		public Microsoft.Xrm.Sdk.EntityReference Contact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy_Delegate
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Select the customer account or contact to provide a quick link to additional customer details, such as account information, activities, and opportunities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		public Microsoft.Xrm.Sdk.EntityReference PotentialCustomer
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
			}
			set
			{
				this.OnPropertyChanging("PotentialCustomer");
				this.SetAttributeValue("customerid", value);
				this.OnPropertyChanged("PotentialCustomer");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the quote, such as the products or services offered or details about the customer's product preferences.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Type the discount amount for the quote if the customer is eligible for special savings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount")]
		public Microsoft.Xrm.Sdk.Money QuoteDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount");
			}
			set
			{
				this.OnPropertyChanging("QuoteDiscountAmount");
				this.SetAttributeValue("discountamount", value);
				this.OnPropertyChanged("QuoteDiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Quote Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount_base")]
		public Microsoft.Xrm.Sdk.Money QuoteDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount_base");
			}
		}
		
		/// <summary>
		/// Type the discount rate that should be applied to the Detail Amount field to include additional savings for the customer in the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountpercentage")]
		public System.Nullable<decimal> QuoteDiscount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("discountpercentage");
			}
			set
			{
				this.OnPropertyChanging("QuoteDiscount");
				this.SetAttributeValue("discountpercentage", value);
				this.OnPropertyChanged("QuoteDiscount");
			}
		}
		
		/// <summary>
		/// Enter the date when the quote pricing is effective or was first communicated to the customer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("effectivefrom")]
		public System.Nullable<System.DateTime> EffectiveFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("effectivefrom");
			}
			set
			{
				this.OnPropertyChanging("EffectiveFrom");
				this.SetAttributeValue("effectivefrom", value);
				this.OnPropertyChanged("EffectiveFrom");
			}
		}
		
		/// <summary>
		/// Enter the expiration date or last day the quote pricing is effective for the customer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("effectiveto")]
		public System.Nullable<System.DateTime> EffectiveTo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("effectiveto");
			}
			set
			{
				this.OnPropertyChanging("EffectiveTo");
				this.SetAttributeValue("effectiveto", value);
				this.OnPropertyChanged("EffectiveTo");
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.OnPropertyChanging("EmailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EmailAddress");
			}
		}
		
		/// <summary>
		/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Enter the date a decision or order is due from the customer to indicate the expiration date of the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expireson")]
		public System.Nullable<System.DateTime> DueBy
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("expireson");
			}
			set
			{
				this.OnPropertyChanging("DueBy");
				this.SetAttributeValue("expireson", value);
				this.OnPropertyChanged("DueBy");
			}
		}
		
		/// <summary>
		/// Type the cost of freight or shipping for the products included in the quote for use in calculating the Total Amount field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount")]
		public Microsoft.Xrm.Sdk.Money FreightAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount");
			}
			set
			{
				this.OnPropertyChanging("FreightAmount");
				this.SetAttributeValue("freightamount", value);
				this.OnPropertyChanged("FreightAmount");
			}
		}
		
		/// <summary>
		/// Value of the Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount_base")]
		public Microsoft.Xrm.Sdk.Money FreightAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount_base");
			}
		}
		
		/// <summary>
		/// Select the freight terms to make sure shipping charges are processed correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue FreightTerms
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("freighttermscode");
			}
			set
			{
				this.OnPropertyChanging("FreightTerms");
				this.SetAttributeValue("freighttermscode", value);
				this.OnPropertyChanged("FreightTerms");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Contains the date time stamp of the last on hold time.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
		public System.Nullable<System.DateTime> LastOnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
			}
			set
			{
				this.OnPropertyChanging("LastOnHoldTime");
				this.SetAttributeValue("lastonholdtime", value);
				this.OnPropertyChanged("LastOnHoldTime");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy_Delegate
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Type a descriptive name for the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Shows the duration in minutes for which the quote was on hold.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
		public System.Nullable<int> OnHoldTime_Minutes
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
			}
		}
		
		/// <summary>
		/// Choose the opportunity that the quote is related to for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
		public Microsoft.Xrm.Sdk.EntityReference Opportunity
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opportunityid");
			}
			set
			{
				this.OnPropertyChanging("Opportunity");
				this.SetAttributeValue("opportunityid", value);
				this.OnPropertyChanged("Opportunity");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> RecordCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("RecordCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("RecordCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference Owner
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("Owner");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("Owner");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Select the payment terms to indicate when the customer needs to pay the total amount.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTerms
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			}
			set
			{
				this.OnPropertyChanging("PaymentTerms");
				this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTerms");
			}
		}
		
		/// <summary>
		/// Choose the price list associated with this record to make sure the products associated with the campaign are offered at the correct prices.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
		public Microsoft.Xrm.Sdk.EntityReference PriceList
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
			}
			set
			{
				this.OnPropertyChanging("PriceList");
				this.SetAttributeValue("pricelevelid", value);
				this.OnPropertyChanged("PriceList");
			}
		}
		
		/// <summary>
		/// Pricing error for the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingError
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			}
			set
			{
				this.OnPropertyChanging("PricingError");
				this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingError");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
		public System.Nullable<System.Guid> QuoteId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("quoteid");
			}
			set
			{
				this.OnPropertyChanging("QuoteId");
				this.SetAttributeValue("quoteid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("QuoteId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.QuoteId = value;
			}
		}
		
		/// <summary>
		/// Shows the quote number for customer reference and searching capabilities. The number cannot be modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotenumber")]
		public string QuoteID
		{
			get
			{
				return this.GetAttributeValue<string>("quotenumber");
			}
			set
			{
				this.OnPropertyChanging("QuoteID");
				this.SetAttributeValue("quotenumber", value);
				this.OnPropertyChanged("QuoteID");
			}
		}
		
		/// <summary>
		/// Enter the delivery date requested by the customer for all products in the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestdeliveryby")]
		public System.Nullable<System.DateTime> RequestedDeliveryDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("requestdeliveryby");
			}
			set
			{
				this.OnPropertyChanging("RequestedDeliveryDate");
				this.SetAttributeValue("requestdeliveryby", value);
				this.OnPropertyChanged("RequestedDeliveryDate");
			}
		}
		
		/// <summary>
		/// Shows the version number of the quote for revision history tracking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("revisionnumber")]
		public System.Nullable<int> RevisionID
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("revisionnumber");
			}
		}
		
		/// <summary>
		/// Select a shipping method for deliveries sent to this address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethod
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			}
			set
			{
				this.OnPropertyChanging("ShippingMethod");
				this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethod");
			}
		}
		
		/// <summary>
		/// Unique identifier of the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_addressid")]
		public System.Nullable<System.Guid> ShipToAddressID
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("shipto_addressid");
			}
			set
			{
				this.OnPropertyChanging("ShipToAddressID");
				this.SetAttributeValue("shipto_addressid", value);
				this.OnPropertyChanged("ShipToAddressID");
			}
		}
		
		/// <summary>
		/// Type the city for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
		public string ShipToCity
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_city");
			}
			set
			{
				this.OnPropertyChanging("ShipToCity");
				this.SetAttributeValue("shipto_city", value);
				this.OnPropertyChanged("ShipToCity");
			}
		}
		
		/// <summary>
		/// Shows the complete Ship To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_composite")]
		public string ShipToAddress
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_composite");
			}
		}
		
		/// <summary>
		/// Type the primary contact name at the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_contactname")]
		public string ShipToContactName
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_contactname");
			}
			set
			{
				this.OnPropertyChanging("ShipToContactName");
				this.SetAttributeValue("shipto_contactname", value);
				this.OnPropertyChanged("ShipToContactName");
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
		public string ShipToCountry_Region
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_country");
			}
			set
			{
				this.OnPropertyChanging("ShipToCountry_Region");
				this.SetAttributeValue("shipto_country", value);
				this.OnPropertyChanged("ShipToCountry_Region");
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
		public string ShipToFax
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_fax");
			}
			set
			{
				this.OnPropertyChanging("ShipToFax");
				this.SetAttributeValue("shipto_fax", value);
				this.OnPropertyChanged("ShipToFax");
			}
		}
		
		/// <summary>
		/// Select the freight terms to make sure shipping orders are processed correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShipToFreightTerms
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
			}
			set
			{
				this.OnPropertyChanging("ShipToFreightTerms");
				this.SetAttributeValue("shipto_freighttermscode", value);
				this.OnPropertyChanged("ShipToFreightTerms");
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
		public string ShipToStreet1
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line1");
			}
			set
			{
				this.OnPropertyChanging("ShipToStreet1");
				this.SetAttributeValue("shipto_line1", value);
				this.OnPropertyChanged("ShipToStreet1");
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
		public string ShipToStreet2
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line2");
			}
			set
			{
				this.OnPropertyChanging("ShipToStreet2");
				this.SetAttributeValue("shipto_line2", value);
				this.OnPropertyChanged("ShipToStreet2");
			}
		}
		
		/// <summary>
		/// Type the third line of the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
		public string ShipToStreet3
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line3");
			}
			set
			{
				this.OnPropertyChanging("ShipToStreet3");
				this.SetAttributeValue("shipto_line3", value);
				this.OnPropertyChanged("ShipToStreet3");
			}
		}
		
		/// <summary>
		/// Type a name for the customer's shipping address, such as "Headquarters" or "Field office",  to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
		public string ShipToName
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_name");
			}
			set
			{
				this.OnPropertyChanging("ShipToName");
				this.SetAttributeValue("shipto_name", value);
				this.OnPropertyChanged("ShipToName");
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
		public string ShipToZIP_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_postalcode");
			}
			set
			{
				this.OnPropertyChanging("ShipToZIP_PostalCode");
				this.SetAttributeValue("shipto_postalcode", value);
				this.OnPropertyChanged("ShipToZIP_PostalCode");
			}
		}
		
		/// <summary>
		/// Type the state or province for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
		public string ShipToState_Province
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_stateorprovince");
			}
			set
			{
				this.OnPropertyChanging("ShipToState_Province");
				this.SetAttributeValue("shipto_stateorprovince", value);
				this.OnPropertyChanged("ShipToState_Province");
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
		public string ShipToPhone
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_telephone");
			}
			set
			{
				this.OnPropertyChanging("ShipToPhone");
				this.SetAttributeValue("shipto_telephone", value);
				this.OnPropertyChanged("ShipToPhone");
			}
		}
		
		/// <summary>
		/// Skip Price Calculation (For Internal use)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculation")]
		public Microsoft.Xrm.Sdk.OptionSetValue SkipPriceCalculation
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
			}
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
				this.SetAttributeValue("skippricecalculation", value);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		
		/// <summary>
		/// Choose the service level agreement (SLA) that you want to apply to the quote record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLA
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			set
			{
				this.OnPropertyChanging("SLA");
				this.SetAttributeValue("slaid", value);
				this.OnPropertyChanged("SLA");
			}
		}
		
		/// <summary>
		/// Last SLA that was applied to this quote. This field is for internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
		public Microsoft.Xrm.Sdk.EntityReference LastSLAApplied
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Shows whether the quote is draft, active, won, or closed. Only draft quotes can be edited.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<QuoteState> Status
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((QuoteState)(System.Enum.ToObject(typeof(QuoteState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("Status");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("Status");
			}
		}
		
		/// <summary>
		/// Select the quote's status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusReason
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusReason");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusReason");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the total amount due, calculated as the sum of the products, discounts, freight, and taxes for the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount")]
		public Microsoft.Xrm.Sdk.Money TotalAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount");
			}
			set
			{
				this.OnPropertyChanging("TotalAmount");
				this.SetAttributeValue("totalamount", value);
				this.OnPropertyChanged("TotalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Total Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total product amount for the quote, minus any discounts. This value is added to freight and tax amounts in the calculation for the total amount due for the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight")]
		public Microsoft.Xrm.Sdk.Money TotalPre_FreightAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight");
			}
			set
			{
				this.OnPropertyChanging("TotalPre_FreightAmount");
				this.SetAttributeValue("totalamountlessfreight", value);
				this.OnPropertyChanged("TotalPre_FreightAmount");
			}
		}
		
		/// <summary>
		/// Value of the Total Pre-Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight_base")]
		public Microsoft.Xrm.Sdk.Money TotalPre_FreightAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight_base");
			}
		}
		
		/// <summary>
		/// Shows the total discount amount, based on the discount price and rate entered on the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount");
			}
			set
			{
				this.OnPropertyChanging("TotalDiscountAmount");
				this.SetAttributeValue("totaldiscountamount", value);
				this.OnPropertyChanged("TotalDiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Total Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the sum of all existing and write-in products included on the quote, based on the specified price list and quantities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount")]
		public Microsoft.Xrm.Sdk.Money TotalDetailAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount");
			}
			set
			{
				this.OnPropertyChanging("TotalDetailAmount");
				this.SetAttributeValue("totallineitemamount", value);
				this.OnPropertyChanged("TotalDetailAmount");
			}
		}
		
		/// <summary>
		/// Value of the Total Detail Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalDetailAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total of the Manual Discount amounts specified on all products included in the quote. This value is reflected in the Detail Amount field on the quote and is added to any discount amount or rate specified on the quote
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount");
			}
			set
			{
				this.OnPropertyChanging("TotalLineItemDiscountAmount");
				this.SetAttributeValue("totallineitemdiscountamount", value);
				this.OnPropertyChanged("TotalLineItemDiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Total Line Item Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total of the Tax amounts specified on all products included in the quote, included in the Total Amount due calculation for the quote.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax")]
		public Microsoft.Xrm.Sdk.Money TotalTax
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax");
			}
			set
			{
				this.OnPropertyChanging("TotalTax");
				this.SetAttributeValue("totaltax", value);
				this.OnPropertyChanged("TotalTax");
			}
		}
		
		/// <summary>
		/// Value of the Total Tax in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax_base")]
		public Microsoft.Xrm.Sdk.Money TotalTax_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax_base");
			}
		}
		
		/// <summary>
		/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference Currency
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("Currency");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("Currency");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Select whether the products included in the quote should be shipped to the specified address or held until the customer calls with further pick up or delivery instructions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
		public System.Nullable<bool> ShipTo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("willcall");
			}
			set
			{
				this.OnPropertyChanging("ShipTo");
				this.SetAttributeValue("willcall", value);
				this.OnPropertyChanged("ShipTo");
			}
		}
		
		
		/// <summary>
		/// N:1 processstage_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("processstage_quotes")]
		public ProcessStage processstage_quotes
		{
			get
			{
				return this.GetRelatedEntity<ProcessStage>("processstage_quotes", null);
			}
			set
			{
				this.OnPropertyChanging("processstage_quotes");
				this.SetRelatedEntity<ProcessStage>("processstage_quotes", null, value);
				this.OnPropertyChanged("processstage_quotes");
			}
		}
	}
}
